[package]
name = "proxy-slint"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.3"
proxyapi = { path = "../proxyapi" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.18"

[build-dependencies]
slint-build = "1.3" 